### ISSUE TITLE
CUDA-error: device-side assert triggered

### ISSUE THREAD

**Issue by Devininthelab** [QwenLM/Qwen2.5-Omni#160]
Hi I'm running for ASR task, using this system prompt:

```
message = [{"role": "system", "content": "You are a speech recognition model."}]
```

And I encountered this issue when running:
```
inputs = inputs.to(model.device).to(model.dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minhthan001/.conda/envs/worldsense/lib/python3.12/site-packages/transformers/feature_extraction_utils.py", line 246, in to
    new_data[k] = v.to(device=device, non_blocking=non_blocking)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [376,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [376,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [376,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [376,0,0], thread: 
(... and so on. It just throw kinda same log as pervious lines)
```

Not sure what happens here. Thanks it advance for your help

**Comment by khufia** [comment]
Hi @Devininthelab, could you please let me know how did you fix this. I run into this error during inference. I get this error after few samples. The first few samples run fine.

**Comment by Devininthelab** [comment]
@khufia Hi, I think last time I solved it by updating to a newer huggingface version. You could see more in here [link](https://github.com/QwenLM/Qwen2.5-Omni/issues/169).
