### ISSUE TITLE
CUDA error: device-side assert triggered while running

### ISSUE THREAD

**Issue by Devininthelab** [QwenLM/Qwen2.5-Omni#169]
Hi everyone, 

I am running Qwen Omni for evaluation on Open_asr librispeech. I am not using the default system prompt, and changed to the system prompt used [here](https://github.com/QwenLM/Qwen2.5-Omni/blob/main/cookbooks/universal_audio_understanding.ipynb), with the hope of reproducing their open_asr librispeech result:

`message = [{"role": "system", "content": "You are a speech recognition model."}]`

However, I encountered the issue, when running on `librispeech_test_clean `, and it's happend after around 52 inference run. 

```
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [272,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [272,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

It keeps repeat many times, and in the end, it throw this final error:
```
File "/home/minhthan001/Projects/lmms-eval/lmms_eval/models/qwen2_5_omni.py", line 329, in generate_until
    inputs = inputs.to(self.model.device).to(self.model.dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minhthan001/.conda/envs/worldsense/lib/python3.12/site-packages/transformers/feature_extraction_utils.py", line 246, in to
    new_data[k] = v.to(device=device, non_blocking=non_blocking)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I also tried the setting, but I still encounter the same error. 

```
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
os.environ['TORCH_USE_CUDA_DSA'] = '1'
```

Following this [thread](https://github.com/openai/whisper/discussions/2313), which I think having the same issue for me, but I still cannot figured out what happened here.  

I would greatly appreciate any insights or suggestions on how to fix this issue!

Thank you!

**Comment by wangxiongts** [comment]
We have updated our transformers code and docker, please refer to readme to get the new version, maybe can solve your problem.

**Comment by Devininthelab** [comment]
@wangxiongts  Hi, thanks a lot for your help. It works perfectly now. 

Also, thanks a lot for the wonderful project.
