### ISSUE TITLE
Qwen2.5-Omni-7B CUDA OOM

### ISSUE THREAD

**Issue by yogkul2000** [QwenLM/Qwen2.5-Omni#257]
I was easily able to do SFT on 4 *48GB GPUs, but running evaluation on video benchmarks like video_mmmu or vinoground (very short videos) gives OOM. Only using 1 GPU and splitting the model across the 4 GPUs (device_map="auto"), the issue still persists.

```
Token indices sequence length is longer than the specified maximum sequence length for this model (115108 > 32768). Running this sequence through the model will result in indexing errors
2025-05-03 13:40:54.819 | ERROR    | lmms_eval.models.qwen2_5_omni:generate_until:302 - Error CUDA out of memory. Tried to allocate 334.76 GiB. GPU 0 has a total capacity of 44.42 GiB of which 27.48 GiB is free. Including non-PyTorch memory, this process has 16.93 GiB memory in use. Of the allocated memory 12.10 GiB is allocated by PyTorch, and 4.32 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) in generating
```

**Comment by wangxiongts** [comment]
Have you used flash attention during evaluations?

**Comment by yogkul2000** [comment]
1. Tried both eager and flash_attn, OOM issue persists.
Manually changing qwen_omni_utils to below values did help but performance is pretty bad.
```
IMAGE_FACTOR = 28
MIN_PIXELS = 4 * 28 * 28
MAX_PIXELS = 108000
MAX_RATIO = 200

VIDEO_MIN_PIXELS = 50176
VIDEO_MAX_PIXELS = 50176

FRAME_FACTOR = 2
FPS = 2.0
FPS_MIN_FRAMES = 4
FPS_MAX_FRAMES = 4
```
2. Another observation is when audio_in_video is True, it increase VRAM usage significantly.

**Comment by yogkul2000** [comment]
It works now.
Python 3.10, CUDA 12.4, PyTorch 2.6.0 and installing flash-attn as below
```
pip install flash-attn -f https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
```
